name = "Fortran90Namelists"
uuid = "8fb689aa-71ff-4044-8071-0cffc910b57d"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Compat = "2.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
